# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vuka_pb2 as vuka__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vuka_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BridgeStub:
    """Bridge exposes the operations the ISO 20022 gateway needs. Cross-border
    transfers (RWF -> KES) are idempotent and write two balanced FX legs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/vuka.v1.Bridge/CreateUser',
                request_serializer=vuka__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=vuka__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/vuka.v1.Bridge/GetBalance',
                request_serializer=vuka__pb2.GetBalanceRequest.SerializeToString,
                response_deserializer=vuka__pb2.GetBalanceResponse.FromString,
                _registered_method=True)
        self.FundAccount = channel.unary_unary(
                '/vuka.v1.Bridge/FundAccount',
                request_serializer=vuka__pb2.FundAccountRequest.SerializeToString,
                response_deserializer=vuka__pb2.TransferResponse.FromString,
                _registered_method=True)
        self.Transfer = channel.unary_unary(
                '/vuka.v1.Bridge/Transfer',
                request_serializer=vuka__pb2.TransferRequest.SerializeToString,
                response_deserializer=vuka__pb2.TransferResponse.FromString,
                _registered_method=True)
        self.CrossBorderTransfer = channel.unary_unary(
                '/vuka.v1.Bridge/CrossBorderTransfer',
                request_serializer=vuka__pb2.CrossBorderRequest.SerializeToString,
                response_deserializer=vuka__pb2.TransferResponse.FromString,
                _registered_method=True)
        self.GetTransfer = channel.unary_unary(
                '/vuka.v1.Bridge/GetTransfer',
                request_serializer=vuka__pb2.GetTransferRequest.SerializeToString,
                response_deserializer=vuka__pb2.TransferResponse.FromString,
                _registered_method=True)
        self.ReverseTransfer = channel.unary_unary(
                '/vuka.v1.Bridge/ReverseTransfer',
                request_serializer=vuka__pb2.ReverseRequest.SerializeToString,
                response_deserializer=vuka__pb2.TransferResponse.FromString,
                _registered_method=True)


class BridgeServicer:
    """Bridge exposes the operations the ISO 20022 gateway needs. Cross-border
    transfers (RWF -> KES) are idempotent and write two balanced FX legs.
    """

    def CreateUser(self, request, context):
        """CreateUser registers a trader and their PERSONAL + BUSINESS wallets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """GetBalance returns the derived balance for an account.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FundAccount(self, request, context):
        """FundAccount credits an external cash-in to an account (idempotent).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transfer(self, request, context):
        """Transfer moves value between two SAME-currency accounts (idempotent).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CrossBorderTransfer(self, request, context):
        """CrossBorderTransfer moves value RWF -> KES through FX settlement legs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransfer(self, request, context):
        """GetTransfer fetches a transfer by id. Returns NOT_FOUND if unknown.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReverseTransfer(self, request, context):
        """ReverseTransfer reverses a SUCCESS transfer (idempotent replay-safe).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=vuka__pb2.CreateUserRequest.FromString,
                    response_serializer=vuka__pb2.CreateUserResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=vuka__pb2.GetBalanceRequest.FromString,
                    response_serializer=vuka__pb2.GetBalanceResponse.SerializeToString,
            ),
            'FundAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.FundAccount,
                    request_deserializer=vuka__pb2.FundAccountRequest.FromString,
                    response_serializer=vuka__pb2.TransferResponse.SerializeToString,
            ),
            'Transfer': grpc.unary_unary_rpc_method_handler(
                    servicer.Transfer,
                    request_deserializer=vuka__pb2.TransferRequest.FromString,
                    response_serializer=vuka__pb2.TransferResponse.SerializeToString,
            ),
            'CrossBorderTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.CrossBorderTransfer,
                    request_deserializer=vuka__pb2.CrossBorderRequest.FromString,
                    response_serializer=vuka__pb2.TransferResponse.SerializeToString,
            ),
            'GetTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransfer,
                    request_deserializer=vuka__pb2.GetTransferRequest.FromString,
                    response_serializer=vuka__pb2.TransferResponse.SerializeToString,
            ),
            'ReverseTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.ReverseTransfer,
                    request_deserializer=vuka__pb2.ReverseRequest.FromString,
                    response_serializer=vuka__pb2.TransferResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vuka.v1.Bridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vuka.v1.Bridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Bridge:
    """Bridge exposes the operations the ISO 20022 gateway needs. Cross-border
    transfers (RWF -> KES) are idempotent and write two balanced FX legs.
    """

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vuka.v1.Bridge/CreateUser',
            vuka__pb2.CreateUserRequest.SerializeToString,
            vuka__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vuka.v1.Bridge/GetBalance',
            vuka__pb2.GetBalanceRequest.SerializeToString,
            vuka__pb2.GetBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FundAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vuka.v1.Bridge/FundAccount',
            vuka__pb2.FundAccountRequest.SerializeToString,
            vuka__pb2.TransferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vuka.v1.Bridge/Transfer',
            vuka__pb2.TransferRequest.SerializeToString,
            vuka__pb2.TransferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CrossBorderTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vuka.v1.Bridge/CrossBorderTransfer',
            vuka__pb2.CrossBorderRequest.SerializeToString,
            vuka__pb2.TransferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vuka.v1.Bridge/GetTransfer',
            vuka__pb2.GetTransferRequest.SerializeToString,
            vuka__pb2.TransferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReverseTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vuka.v1.Bridge/ReverseTransfer',
            vuka__pb2.ReverseRequest.SerializeToString,
            vuka__pb2.TransferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
