// VUKA Bridge gRPC contract.
//
// This is the single source of truth for inter-service messaging between the
// Python ISO 20022 gateway (client) and the Go core engine (server). The Go
// ledger engine is the authority: every RPC maps 1:1 to a ledger.Service
// method, so the gateway never mutates state itself.
//
// Identifiers that are UUIDs in the domain travel as plain strings here (we
// avoid java-style wrappers). Money amounts are carried as double but rounded
// to 4 decimal places (matching NUMERIC(18,4)) by the engine before write.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: vuka.proto

package grpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FullName          string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PhoneNumber       string                 `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	BusinessRegNumber string                 `protobuf:"bytes,3,opt,name=business_reg_number,json=businessRegNumber,proto3" json:"business_reg_number,omitempty"`
	Currency          string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"` // default "RWF"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_vuka_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vuka_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_vuka_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateUserRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateUserRequest) GetBusinessRegNumber() string {
	if x != nil {
		return x.BusinessRegNumber
	}
	return ""
}

func (x *CreateUserRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Accounts      []*Account             `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_vuka_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vuka_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_vuka_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CreateUserResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type User struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName          string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PhoneNumber       string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	BusinessRegNumber string                 `protobuf:"bytes,4,opt,name=business_reg_number,json=businessRegNumber,proto3" json:"business_reg_number,omitempty"`
	KycStatus         string                 `protobuf:"bytes,5,opt,name=kyc_status,json=kycStatus,proto3" json:"kyc_status,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_vuka_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_vuka_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_vuka_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetBusinessRegNumber() string {
	if x != nil {
		return x.BusinessRegNumber
	}
	return ""
}

func (x *User) GetKycStatus() string {
	if x != nil {
		return x.KycStatus
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // PERSONAL | BUSINESS | SETTLEMENT | FEES
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_vuka_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_vuka_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_vuka_proto_rawDescGZIP(), []int{3}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Account) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_vuka_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vuka_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_vuka_proto_rawDescGZIP(), []int{4}
}

func (x *GetBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_vuka_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vuka_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_vuka_proto_rawDescGZIP(), []int{5}
}

func (x *GetBalanceResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetBalanceResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetBalanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetBalanceResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type FundAccountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // UUIDv4
	Amount         float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Reference      string                 `protobuf:"bytes,5,opt,name=reference,proto3" json:"reference,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FundAccountRequest) Reset() {
	*x = FundAccountRequest{}
	mi := &file_vuka_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundAccountRequest) ProtoMessage() {}

func (x *FundAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vuka_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundAccountRequest.ProtoReflect.Descriptor instead.
func (*FundAccountRequest) Descriptor() ([]byte, []int) {
	return file_vuka_proto_rawDescGZIP(), []int{6}
}

func (x *FundAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *FundAccountRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *FundAccountRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *FundAccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FundAccountRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

type TransferRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey       string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // UUIDv4
	SourceAccountId      string                 `protobuf:"bytes,2,opt,name=source_account_id,json=sourceAccountId,proto3" json:"source_account_id,omitempty"`
	DestinationAccountId string                 `protobuf:"bytes,3,opt,name=destination_account_id,json=destinationAccountId,proto3" json:"destination_account_id,omitempty"`
	Amount               float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	InvoiceNumber        string                 `protobuf:"bytes,6,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_vuka_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vuka_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_vuka_proto_rawDescGZIP(), []int{7}
}

func (x *TransferRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TransferRequest) GetSourceAccountId() string {
	if x != nil {
		return x.SourceAccountId
	}
	return ""
}

func (x *TransferRequest) GetDestinationAccountId() string {
	if x != nil {
		return x.DestinationAccountId
	}
	return ""
}

func (x *TransferRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransferRequest) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

type CrossBorderRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey       string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`                     // UUIDv4
	SourceAccountId      string                 `protobuf:"bytes,2,opt,name=source_account_id,json=sourceAccountId,proto3" json:"source_account_id,omitempty"`                // RWF BUSINESS wallet (Rwanda importer)
	DestinationAccountId string                 `protobuf:"bytes,3,opt,name=destination_account_id,json=destinationAccountId,proto3" json:"destination_account_id,omitempty"` // KES BUSINESS wallet (Kenya supplier)
	Amount               float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`                                                         // in currency_from (RWF)
	CurrencyFrom         string                 `protobuf:"bytes,5,opt,name=currency_from,json=currencyFrom,proto3" json:"currency_from,omitempty"`                           // default "RWF"
	CurrencyTo           string                 `protobuf:"bytes,6,opt,name=currency_to,json=currencyTo,proto3" json:"currency_to,omitempty"`                                 // default "KES"
	FxRate               float64                `protobuf:"fixed64,7,opt,name=fx_rate,json=fxRate,proto3" json:"fx_rate,omitempty"`                                           // optional; engine falls back to env default
	InvoiceNumber        string                 `protobuf:"bytes,8,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CrossBorderRequest) Reset() {
	*x = CrossBorderRequest{}
	mi := &file_vuka_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossBorderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossBorderRequest) ProtoMessage() {}

func (x *CrossBorderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vuka_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossBorderRequest.ProtoReflect.Descriptor instead.
func (*CrossBorderRequest) Descriptor() ([]byte, []int) {
	return file_vuka_proto_rawDescGZIP(), []int{8}
}

func (x *CrossBorderRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CrossBorderRequest) GetSourceAccountId() string {
	if x != nil {
		return x.SourceAccountId
	}
	return ""
}

func (x *CrossBorderRequest) GetDestinationAccountId() string {
	if x != nil {
		return x.DestinationAccountId
	}
	return ""
}

func (x *CrossBorderRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CrossBorderRequest) GetCurrencyFrom() string {
	if x != nil {
		return x.CurrencyFrom
	}
	return ""
}

func (x *CrossBorderRequest) GetCurrencyTo() string {
	if x != nil {
		return x.CurrencyTo
	}
	return ""
}

func (x *CrossBorderRequest) GetFxRate() float64 {
	if x != nil {
		return x.FxRate
	}
	return 0
}

func (x *CrossBorderRequest) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

type GetTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferRequest) Reset() {
	*x = GetTransferRequest{}
	mi := &file_vuka_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferRequest) ProtoMessage() {}

func (x *GetTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vuka_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferRequest.ProtoReflect.Descriptor instead.
func (*GetTransferRequest) Descriptor() ([]byte, []int) {
	return file_vuka_proto_rawDescGZIP(), []int{9}
}

func (x *GetTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

type ReverseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseRequest) Reset() {
	*x = ReverseRequest{}
	mi := &file_vuka_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseRequest) ProtoMessage() {}

func (x *ReverseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vuka_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseRequest.ProtoReflect.Descriptor instead.
func (*ReverseRequest) Descriptor() ([]byte, []int) {
	return file_vuka_proto_rawDescGZIP(), []int{10}
}

func (x *ReverseRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *ReverseRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TransferResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdempotencyKey       string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	InvoiceNumber        string                 `protobuf:"bytes,3,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	SourceAccountId      string                 `protobuf:"bytes,4,opt,name=source_account_id,json=sourceAccountId,proto3" json:"source_account_id,omitempty"`
	DestinationAccountId string                 `protobuf:"bytes,5,opt,name=destination_account_id,json=destinationAccountId,proto3" json:"destination_account_id,omitempty"`
	Amount               float64                `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`             // currency of the source leg / request
	Status               string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`                 // SUCCESS | FAILED | REVERSED | ...
	FxRate               float64                `protobuf:"fixed64,9,opt,name=fx_rate,json=fxRate,proto3" json:"fx_rate,omitempty"` // 0 for same-currency transfers
	ExternalReference    string                 `protobuf:"bytes,10,opt,name=external_reference,json=externalReference,proto3" json:"external_reference,omitempty"`
	FailureReason        string                 `protobuf:"bytes,11,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Replayed             bool                   `protobuf:"varint,14,opt,name=replayed,proto3" json:"replayed,omitempty"` // true when the idempotency key was replayed
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_vuka_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vuka_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_vuka_proto_rawDescGZIP(), []int{11}
}

func (x *TransferResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransferResponse) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TransferResponse) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

func (x *TransferResponse) GetSourceAccountId() string {
	if x != nil {
		return x.SourceAccountId
	}
	return ""
}

func (x *TransferResponse) GetDestinationAccountId() string {
	if x != nil {
		return x.DestinationAccountId
	}
	return ""
}

func (x *TransferResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransferResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransferResponse) GetFxRate() float64 {
	if x != nil {
		return x.FxRate
	}
	return 0
}

func (x *TransferResponse) GetExternalReference() string {
	if x != nil {
		return x.ExternalReference
	}
	return ""
}

func (x *TransferResponse) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *TransferResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TransferResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *TransferResponse) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

var File_vuka_proto protoreflect.FileDescriptor

const file_vuka_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"vuka.proto\x12\avuka.v1\"\x9f\x01\n" +
	"\x11CreateUserRequest\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12!\n" +
	"\fphone_number\x18\x02 \x01(\tR\vphoneNumber\x12.\n" +
	"\x13business_reg_number\x18\x03 \x01(\tR\x11businessRegNumber\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"e\n" +
	"\x12CreateUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.vuka.v1.UserR\x04user\x12,\n" +
	"\baccounts\x18\x02 \x03(\v2\x10.vuka.v1.AccountR\baccounts\"\xc4\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12.\n" +
	"\x13business_reg_number\x18\x04 \x01(\tR\x11businessRegNumber\x12\x1d\n" +
	"\n" +
	"kyc_status\x18\x05 \x01(\tR\tkycStatus\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\x81\x01\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"2\n" +
	"\x11GetBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"{\n" +
	"\x12GetBalanceResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\"\xae\x01\n" +
	"\x12FundAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1c\n" +
	"\treference\x18\x05 \x01(\tR\treference\"\xf7\x01\n" +
	"\x0fTransferRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12*\n" +
	"\x11source_account_id\x18\x02 \x01(\tR\x0fsourceAccountId\x124\n" +
	"\x16destination_account_id\x18\x03 \x01(\tR\x14destinationAccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12%\n" +
	"\x0einvoice_number\x18\x06 \x01(\tR\rinvoiceNumber\"\xbd\x02\n" +
	"\x12CrossBorderRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12*\n" +
	"\x11source_account_id\x18\x02 \x01(\tR\x0fsourceAccountId\x124\n" +
	"\x16destination_account_id\x18\x03 \x01(\tR\x14destinationAccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12#\n" +
	"\rcurrency_from\x18\x05 \x01(\tR\fcurrencyFrom\x12\x1f\n" +
	"\vcurrency_to\x18\x06 \x01(\tR\n" +
	"currencyTo\x12\x17\n" +
	"\afx_rate\x18\a \x01(\x01R\x06fxRate\x12%\n" +
	"\x0einvoice_number\x18\b \x01(\tR\rinvoiceNumber\"5\n" +
	"\x12GetTransferRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\"I\n" +
	"\x0eReverseRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xe9\x03\n" +
	"\x10TransferResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0einvoice_number\x18\x03 \x01(\tR\rinvoiceNumber\x12*\n" +
	"\x11source_account_id\x18\x04 \x01(\tR\x0fsourceAccountId\x124\n" +
	"\x16destination_account_id\x18\x05 \x01(\tR\x14destinationAccountId\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x17\n" +
	"\afx_rate\x18\t \x01(\x01R\x06fxRate\x12-\n" +
	"\x12external_reference\x18\n" +
	" \x01(\tR\x11externalReference\x12%\n" +
	"\x0efailure_reason\x18\v \x01(\tR\rfailureReason\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\x12\x1a\n" +
	"\breplayed\x18\x0e \x01(\bR\breplayed2\xfb\x03\n" +
	"\x06Bridge\x12E\n" +
	"\n" +
	"CreateUser\x12\x1a.vuka.v1.CreateUserRequest\x1a\x1b.vuka.v1.CreateUserResponse\x12E\n" +
	"\n" +
	"GetBalance\x12\x1a.vuka.v1.GetBalanceRequest\x1a\x1b.vuka.v1.GetBalanceResponse\x12E\n" +
	"\vFundAccount\x12\x1b.vuka.v1.FundAccountRequest\x1a\x19.vuka.v1.TransferResponse\x12?\n" +
	"\bTransfer\x12\x18.vuka.v1.TransferRequest\x1a\x19.vuka.v1.TransferResponse\x12M\n" +
	"\x13CrossBorderTransfer\x12\x1b.vuka.v1.CrossBorderRequest\x1a\x19.vuka.v1.TransferResponse\x12E\n" +
	"\vGetTransfer\x12\x1b.vuka.v1.GetTransferRequest\x1a\x19.vuka.v1.TransferResponse\x12E\n" +
	"\x0fReverseTransfer\x12\x17.vuka.v1.ReverseRequest\x1a\x19.vuka.v1.TransferResponseB,Z*vuka/go-bridge-core/internal/grpcpb;grpcpbb\x06proto3"

var (
	file_vuka_proto_rawDescOnce sync.Once
	file_vuka_proto_rawDescData []byte
)

func file_vuka_proto_rawDescGZIP() []byte {
	file_vuka_proto_rawDescOnce.Do(func() {
		file_vuka_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vuka_proto_rawDesc), len(file_vuka_proto_rawDesc)))
	})
	return file_vuka_proto_rawDescData
}

var file_vuka_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_vuka_proto_goTypes = []any{
	(*CreateUserRequest)(nil),  // 0: vuka.v1.CreateUserRequest
	(*CreateUserResponse)(nil), // 1: vuka.v1.CreateUserResponse
	(*User)(nil),               // 2: vuka.v1.User
	(*Account)(nil),            // 3: vuka.v1.Account
	(*GetBalanceRequest)(nil),  // 4: vuka.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil), // 5: vuka.v1.GetBalanceResponse
	(*FundAccountRequest)(nil), // 6: vuka.v1.FundAccountRequest
	(*TransferRequest)(nil),    // 7: vuka.v1.TransferRequest
	(*CrossBorderRequest)(nil), // 8: vuka.v1.CrossBorderRequest
	(*GetTransferRequest)(nil), // 9: vuka.v1.GetTransferRequest
	(*ReverseRequest)(nil),     // 10: vuka.v1.ReverseRequest
	(*TransferResponse)(nil),   // 11: vuka.v1.TransferResponse
}
var file_vuka_proto_depIdxs = []int32{
	2,  // 0: vuka.v1.CreateUserResponse.user:type_name -> vuka.v1.User
	3,  // 1: vuka.v1.CreateUserResponse.accounts:type_name -> vuka.v1.Account
	0,  // 2: vuka.v1.Bridge.CreateUser:input_type -> vuka.v1.CreateUserRequest
	4,  // 3: vuka.v1.Bridge.GetBalance:input_type -> vuka.v1.GetBalanceRequest
	6,  // 4: vuka.v1.Bridge.FundAccount:input_type -> vuka.v1.FundAccountRequest
	7,  // 5: vuka.v1.Bridge.Transfer:input_type -> vuka.v1.TransferRequest
	8,  // 6: vuka.v1.Bridge.CrossBorderTransfer:input_type -> vuka.v1.CrossBorderRequest
	9,  // 7: vuka.v1.Bridge.GetTransfer:input_type -> vuka.v1.GetTransferRequest
	10, // 8: vuka.v1.Bridge.ReverseTransfer:input_type -> vuka.v1.ReverseRequest
	1,  // 9: vuka.v1.Bridge.CreateUser:output_type -> vuka.v1.CreateUserResponse
	5,  // 10: vuka.v1.Bridge.GetBalance:output_type -> vuka.v1.GetBalanceResponse
	11, // 11: vuka.v1.Bridge.FundAccount:output_type -> vuka.v1.TransferResponse
	11, // 12: vuka.v1.Bridge.Transfer:output_type -> vuka.v1.TransferResponse
	11, // 13: vuka.v1.Bridge.CrossBorderTransfer:output_type -> vuka.v1.TransferResponse
	11, // 14: vuka.v1.Bridge.GetTransfer:output_type -> vuka.v1.TransferResponse
	11, // 15: vuka.v1.Bridge.ReverseTransfer:output_type -> vuka.v1.TransferResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_vuka_proto_init() }
func file_vuka_proto_init() {
	if File_vuka_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vuka_proto_rawDesc), len(file_vuka_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vuka_proto_goTypes,
		DependencyIndexes: file_vuka_proto_depIdxs,
		MessageInfos:      file_vuka_proto_msgTypes,
	}.Build()
	File_vuka_proto = out.File
	file_vuka_proto_goTypes = nil
	file_vuka_proto_depIdxs = nil
}
