// VUKA Bridge gRPC contract.
//
// This is the single source of truth for inter-service messaging between the
// Python ISO 20022 gateway (client) and the Go core engine (server). The Go
// ledger engine is the authority: every RPC maps 1:1 to a ledger.Service
// method, so the gateway never mutates state itself.
//
// Identifiers that are UUIDs in the domain travel as plain strings here (we
// avoid java-style wrappers). Money amounts are carried as double but rounded
// to 4 decimal places (matching NUMERIC(18,4)) by the engine before write.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: vuka.proto

package grpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Bridge_CreateUser_FullMethodName          = "/vuka.v1.Bridge/CreateUser"
	Bridge_GetBalance_FullMethodName          = "/vuka.v1.Bridge/GetBalance"
	Bridge_FundAccount_FullMethodName         = "/vuka.v1.Bridge/FundAccount"
	Bridge_Transfer_FullMethodName            = "/vuka.v1.Bridge/Transfer"
	Bridge_CrossBorderTransfer_FullMethodName = "/vuka.v1.Bridge/CrossBorderTransfer"
	Bridge_GetTransfer_FullMethodName         = "/vuka.v1.Bridge/GetTransfer"
	Bridge_ReverseTransfer_FullMethodName     = "/vuka.v1.Bridge/ReverseTransfer"
)

// BridgeClient is the client API for Bridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Bridge exposes the operations the ISO 20022 gateway needs. Cross-border
// transfers (RWF -> KES) are idempotent and write two balanced FX legs.
type BridgeClient interface {
	// CreateUser registers a trader and their PERSONAL + BUSINESS wallets.
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	// GetBalance returns the derived balance for an account.
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	// FundAccount credits an external cash-in to an account (idempotent).
	FundAccount(ctx context.Context, in *FundAccountRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	// Transfer moves value between two SAME-currency accounts (idempotent).
	Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	// CrossBorderTransfer moves value RWF -> KES through FX settlement legs.
	CrossBorderTransfer(ctx context.Context, in *CrossBorderRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	// GetTransfer fetches a transfer by id. Returns NOT_FOUND if unknown.
	GetTransfer(ctx context.Context, in *GetTransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	// ReverseTransfer reverses a SUCCESS transfer (idempotent replay-safe).
	ReverseTransfer(ctx context.Context, in *ReverseRequest, opts ...grpc.CallOption) (*TransferResponse, error)
}

type bridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewBridgeClient(cc grpc.ClientConnInterface) BridgeClient {
	return &bridgeClient{cc}
}

func (c *bridgeClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, Bridge_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, Bridge_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeClient) FundAccount(ctx context.Context, in *FundAccountRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, Bridge_FundAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeClient) Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, Bridge_Transfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeClient) CrossBorderTransfer(ctx context.Context, in *CrossBorderRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, Bridge_CrossBorderTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeClient) GetTransfer(ctx context.Context, in *GetTransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, Bridge_GetTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeClient) ReverseTransfer(ctx context.Context, in *ReverseRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, Bridge_ReverseTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BridgeServer is the server API for Bridge service.
// All implementations must embed UnimplementedBridgeServer
// for forward compatibility.
//
// Bridge exposes the operations the ISO 20022 gateway needs. Cross-border
// transfers (RWF -> KES) are idempotent and write two balanced FX legs.
type BridgeServer interface {
	// CreateUser registers a trader and their PERSONAL + BUSINESS wallets.
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	// GetBalance returns the derived balance for an account.
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	// FundAccount credits an external cash-in to an account (idempotent).
	FundAccount(context.Context, *FundAccountRequest) (*TransferResponse, error)
	// Transfer moves value between two SAME-currency accounts (idempotent).
	Transfer(context.Context, *TransferRequest) (*TransferResponse, error)
	// CrossBorderTransfer moves value RWF -> KES through FX settlement legs.
	CrossBorderTransfer(context.Context, *CrossBorderRequest) (*TransferResponse, error)
	// GetTransfer fetches a transfer by id. Returns NOT_FOUND if unknown.
	GetTransfer(context.Context, *GetTransferRequest) (*TransferResponse, error)
	// ReverseTransfer reverses a SUCCESS transfer (idempotent replay-safe).
	ReverseTransfer(context.Context, *ReverseRequest) (*TransferResponse, error)
	mustEmbedUnimplementedBridgeServer()
}

// UnimplementedBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBridgeServer struct{}

func (UnimplementedBridgeServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedBridgeServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedBridgeServer) FundAccount(context.Context, *FundAccountRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FundAccount not implemented")
}
func (UnimplementedBridgeServer) Transfer(context.Context, *TransferRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Transfer not implemented")
}
func (UnimplementedBridgeServer) CrossBorderTransfer(context.Context, *CrossBorderRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrossBorderTransfer not implemented")
}
func (UnimplementedBridgeServer) GetTransfer(context.Context, *GetTransferRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransfer not implemented")
}
func (UnimplementedBridgeServer) ReverseTransfer(context.Context, *ReverseRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReverseTransfer not implemented")
}
func (UnimplementedBridgeServer) mustEmbedUnimplementedBridgeServer() {}
func (UnimplementedBridgeServer) testEmbeddedByValue()                {}

// UnsafeBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BridgeServer will
// result in compilation errors.
type UnsafeBridgeServer interface {
	mustEmbedUnimplementedBridgeServer()
}

func RegisterBridgeServer(s grpc.ServiceRegistrar, srv BridgeServer) {
	// If the following call panics, it indicates UnimplementedBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Bridge_ServiceDesc, srv)
}

func _Bridge_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bridge_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bridge_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bridge_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bridge_FundAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FundAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).FundAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bridge_FundAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).FundAccount(ctx, req.(*FundAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bridge_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bridge_Transfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).Transfer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bridge_CrossBorderTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrossBorderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).CrossBorderTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bridge_CrossBorderTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).CrossBorderTransfer(ctx, req.(*CrossBorderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bridge_GetTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).GetTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bridge_GetTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).GetTransfer(ctx, req.(*GetTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bridge_ReverseTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).ReverseTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bridge_ReverseTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).ReverseTransfer(ctx, req.(*ReverseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Bridge_ServiceDesc is the grpc.ServiceDesc for Bridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vuka.v1.Bridge",
	HandlerType: (*BridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Bridge_CreateUser_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _Bridge_GetBalance_Handler,
		},
		{
			MethodName: "FundAccount",
			Handler:    _Bridge_FundAccount_Handler,
		},
		{
			MethodName: "Transfer",
			Handler:    _Bridge_Transfer_Handler,
		},
		{
			MethodName: "CrossBorderTransfer",
			Handler:    _Bridge_CrossBorderTransfer_Handler,
		},
		{
			MethodName: "GetTransfer",
			Handler:    _Bridge_GetTransfer_Handler,
		},
		{
			MethodName: "ReverseTransfer",
			Handler:    _Bridge_ReverseTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vuka.proto",
}
